# Generated by Django 3.1.3 on 2021-07-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood'),
        ),
    ]
